---

- name: Update apt cache if needed.
  apt:
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  when: ansible_os_family == "Debian"

- name: Ensure required packages are installed.
  package:
    name: unzip
    state: present
