---

- name: Disable certificate.
  become: true
  become_user: "{{ acmesh_user }}"
  command:
    chdir: "{{ acmesh_user_home }}"
    cmd: >-
      {{ acmesh_cmd_base }} --remove
      -d {{ _acmesh_crt.domains | first }}
      {{- (item == 'ecc') | ternary(' --ecc', '') }}
  with_items: "{{ _acmesh_crt_type_list }}"
  when:
    - _acmesh_crt_dir_stat[item].exists
  changed_when: >-
    _result.rc == 0
  failed_when: >-
    _result.rc > 0 and
    _result.stderr | regex_search((_acmesh_crt.domains | first) ~ ' is already removed') is none
  ignore_errors: "{{ acmesh_ignore_cert_errors }}"
  register: _result
