---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache if needed.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"
      changed_when: false

    - name: Update apt cache if needed.
      apt:
        name: bcron
      when: ansible_os_family == "Debian"
      changed_when: false

  roles:
    - role: xolyu.acmesh
      acmesh_ensure_requirements: yes
